CC = g++
CFLAGS  = -g -Wall -std=c++17
Language = cpp

Target1 = functions_tuples
Target2 = tuple

main:
	$(CC) $(CFLAGS) $(Target1).$(Language) -o $(Target1)
	$(CC) $(CFLAGS) $(Target2).$(Language) -o $(Target2)

clean:
	$(RM) $(Target1)
	$(RM) $(Target2)
	