CC = g++
CFLAGS  = -g -Wall -std=c++17
Language = cpp

main:
	$(CC) $(CFLAGS) main.$(Language) -o main
	$(CC) $(CFLAGS) custom_unordered_map.$(Language) -o custom_unordered_map
clean:
	$(RM) main
	$(RM) custom_unordered_map
	