CC = g++
CFLAGS  = -g -Wall -std=c++17
Language = cpp

main:
	$(CC) $(CFLAGS) main.$(Language) -o main 
	$(CC) $(CFLAGS) iterator_range.$(Language) -o iterator_range
	$(CC) $(CFLAGS) Reverse_iterators.$(Language) -o Reverse_iterators
clean:
	$(RM) main
	$(RM) iterator_range
	$(RM) Reverse_iterators
	